### ISSUE TITLE
pip installs not cached

### ISSUE THREAD

**Issue by derrend** [jpetazzo/squid-in-a-can#19]
Hi, love this docker container, definitely saved me lots of bandwidth during my development but unfortunately when the requirements.txt file is executed during builds 'pip' installs do not seem to be cached.
Please can someone let me know if it is possible to enable this?
Many thanks :)

**Comment by jfroche** [comment]
pip install uses https://pypi.python.org/simple by default. https support is explained in the [README](https://github.com/jpetazzo/squid-in-a-can/blob/master/README.md).
We use a pypi mirror (using [devpi](http://doc.devpi.net/latest/)) in our private network for this (which act as a local cache and our private egg registry).
