### ISSUE TITLE
Document HTTPS CONNECT support in default config

### ISSUE THREAD

**Issue by fkautz** [jpetazzo/squid-in-a-can#26]
The default config doesn't support MITM but does support CONNECT which will proxy and tunnel HTTPS.

We should document this.

**Comment by jpetazzo** [comment]
Where would be the best place to document that? Just a note in the README?

On Mon, Jun 6, 2016 at 2:32 PM, Frederick F. Kautz IV <
notifications@github.com> wrote:

> The default config doesn't support MITM but does support CONNECT which
> will proxy and tunnel HTTPS.
>
> We should document this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jpetazzo/squid-in-a-can/issues/26>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAKd2ekokPqM_mnBQFTyKG_ilem6XNIEks5qJJHdgaJpZM4IvVpN>
> .
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
http://jpetazzo.github.io/
<http://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/>

**Comment by fkautz** [comment]
@jpetazzo Yea, I'll open a PR for it.
