### ISSUE TITLE
DockerHub builds are failing

### ISSUE THREAD

**Issue by lovato** [jpetazzo/squid-in-a-can#35]
Looks like project structure is different, so for the past 2 years, builds are not working.
So I assume that the image I can get from docker hub is 3yo, right?

Best
Lovato

**Comment by jpetazzo** [comment]
Hi!

I didn't even remember that I had an image for this on the Docker Hub. But it should be really straightforward to build it if you need it!

Note that I'm not maintaining this project anymore, though. "Buyer's beware" ;-)

**Comment by lovato** [comment]
OK. Thanks for the answer. I abandoned the idea for now. If needed, I will build it myself.

**Comment by dashohoxha** [comment]
@lovato Give a try to this one: https://github.com/docker-scripts/squid
I am not using it myself right now, but I am not aware of any problems either. In case of any problems I am willing to try and fix it.

**Comment by lovato** [comment]
Ok. Thanks for the tip.
