### ISSUE TITLE
Permission problems with persistent cache

### ISSUE THREAD

**Issue by schmunk42** [jpetazzo/squid-in-a-can#6]
I was trying to mount a cache volume into my container, but got this error:

```
squid_1 | 2014/12/01 06:13:12 kid1| Making directories in /var/cache/squid3/00
squid_1 | FATAL: Failed to make swap directory /var/cache/squid3/00/00: (13) Permission denied
```

The directories get permissions of my user (on my host) and docker can't create the subdirectories...

```
$ ls -la tmp/squid3/
total 0
drwxrwxrwx+ 3 tobias  staff  102 Dec  1 23:52 .
drwxr-xr-x+ 3 tobias  staff  102 Dec  1 23:43 ..
drwxr-xr-x+ 2 tobias  staff   68 Dec  1 23:52 00
```

Running Docker 1.3.1 on OS X 10.10.

[addon]
I was able to get it running on OS X (via docker host vm) by manually creating `/var/cache/squid3/00` to `/var/cache/squid3/0F` and running `chmod -R 777 path/to/volume`.

**Comment by codingtony** [comment]
@schmunk42 
Another work around that works on OSX.
Using a data volume container :

```
docker run -v /var/cache/squid3   --name "squidcache" tianon/true
docker run --net host --name squid --volumes-from squidcache -d jpetazzo/squid-in-a-can 
```
The data is persisted in the container "squidcache"

One can see what's persisted with this command :
```
docker run --volumes-from squidcache  --rm -ti busybox
```
Once in the shell you can go to /var/cache/squid3
